# -*- coding: utf-8 -*-
{
    'name': 'Interfaz Opus Control Integral',
    'summary': 'Interfaz para intercambio de datos entre Opus Control Integral y Odoo 15',
    'description': 'Permite el intercambio de datos entre Opus 2021 Control Integral y Odoo 15.',
    'author': 'ECOSOFT, S. DE R.L. DE C.V.',
    'website': 'http://www.ecosoft.com.mx',
    'category': 'EcoSoft',
    'version': '15.0.20220331',
    'application': False,
    'depends': [
        'base',
        'product',
        'purchase',
        'project',
        'stock',
        'account',
        'account_accountant',
        'resource',
        'purchase_requisition',
    ],
    'data': [
        'security/opus_interface_security.xml',
        'security/ir.model.access.csv',
        'views/contratista.xml',
        'views/contrato.xml',
        'views/factura.xml',
        'views/proyecto_views.xml',
        # 'views/purchase_order_opus_view.xml',
        'views/proyecto_mvg_view.xml',
        'views/required_settings.xml',
    ],
    'demo': [],
}
